- id: doi:10.1016/j.xpro.2023.102769
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166723007360-fx1.jpg

- id: doi:10.1002/ece3.10394
  type: paper
  image: https://github.com/nobuaki-mzmt/tmanual/raw/main/images/output.gif

- id: 10.1016/j.isci.2023.106418
  type: paper
  image: https://www.cell.com/cms/attachment/7c371333-2e51-4206-99f7-cf419502554c/fx1.jpg

- id: 10.1073/pnas.2212401119
  type: paper
  image: https://lh3.googleusercontent.com/XceoqL76F_ZjxiGaWRv8HE23lU0QF1i-VOU6iRkqdk-7Zdhmvww552AmjZuv7bbJeGtZ-iK9-aiJJAMWt6ts1oDLgu_rI5-2c-uCSjWlBHMHHU4DhQXYwRvYDImboKEJFw=w1280
  
- id: 10.1111/evo.14457
  type: paper
  image: https://lh5.googleusercontent.com/-p8tkkjmem3M4xpNQA1ZLBnvXRY6ExRwmQisZloHnK_PYeQg1kwlXhnV9o6sKzPKoCvDQvEjoPcdnbrzyqlL7bj8N4sKrIoQ3Xpqqf7qqVxtT2swpEWnS2tCa4OdXU29iQ=w1280
  
- id: 10.1098/rspb.2021.1458
  type: paper
  image: https://www.oist.jp/sites/default/files/styles/background_image_xl_low_1x/public/20220114-HeaderImage-AColonyOfTermites.jpg?h=56b840cf&itok=_CJhu3rn
  
- id: 10.1098/rspb.2021.0998
  type: paper
  image: https://lh4.googleusercontent.com/R0Mt3WJYCzr5OxSgGhl87NtYH4YcEorwA4G-hE51onN2pTf0goLYQ0LpfDNN_76Boy0m3d1L7lFoyew2u9lcQQ4o0HuVjCLU8b9or6xyZL5YzDpvdwGq274Rcvdm5UYC3g=w1280

- id: 10.1093/aesa/saaa017
  type: paper
  image: https://lh5.googleusercontent.com/Ojv44KfKGayQkj5tRSWnVRwno5gxeB7ye1fiVRuqYpKxk9KwejT-Ms1pxrTZ4mqYrLeX3nugkVoFmJEezTIVgo2Wi52FJJpQkWbfFjGhsNjExf7bL12N_Ddn_UVEK8nHDg=w1280

- id: 10.1086/711020
  type: paper
  image: https://lh4.googleusercontent.com/4sYFurn62gAYuoaLOoVUnmO14HSBaDlFYKLiS__rG1vlGa5Gu_iI8gmknbZBLOiZ-XLHOIrNPxWyuUvM4nE1B36KO1lw719y3utCDj1RfNuDngOr9FT3wQJE61jTBJECAg=w1280

- id: 10.1126/sciadv.aau6108
  type: paper
  image: https://lh6.googleusercontent.com/qzn-N75FRUx_MRWGFVu_cDwh5esZL4FheclHlCfgUDU78gGDoPOUsCxgoHYnVf3Xxk9LG6bDOh0M-0IKU-LxxfBYJLsSETAOUXqb_I1yhwEpR6o7hmFXc3QFenD0A8uVlg=w1280

- id: 10.1098/rsif.2017.0086
  type: paper
  image: https://lh5.googleusercontent.com/8r-UZU2CGkc2MiWDvZeOVTiSBG7J3b2ggPg-cNib8uPCqQxsi0vzzqfta0XSUJF0eSUnmphXP8F74zWSKAh72sc=w1280

- id: 10.1098/rsos.150360
  type: paper
  image: https://lh4.googleusercontent.com/OlOrNdIYwJts4LIpiDWhN0JRO_e7zIx9haxlcIwecvShT5C7wlU_ChOEA63xfLECxsp2EQ=w1280

- id: 10.1016/j.anbehav.2016.07.007 
  type: paper
  image: https://lh5.googleusercontent.com/H7VYXvtW7G8vg5B8G6-aQ_mXY2j0z0z1XZ0oQQ35dtGECaXa2Aurnnj8IC9jayfsxOFgVAn0u25_t3EBx4yArwBDH9G2HU-_A2bwtkn5vFhg9l09=w1280

- id: 10.1007/s00040-013-0319-1
  type: paper
  image: https://lh4.googleusercontent.com/Cpz41bRFSuUzueWVMA-iXPWI7pUo2XvqveE45rWc6UhmmaAzO_u9lKaDB7DdeAKOb8ORXTK-C4C0zpDTJGhSwPnRKky-SyG2DgIBfmbgAnmdkxFn=w1280
