
# 2023
# 33. Tanaka Y., Valentini G., Pratt. C. S., Shimoji H., & Mizumoto N.* (2023) Obtaining long movement trajectories of leaders and followers in ant tandem runs. STAR Protocols, 4(4):102769, DOI: 10.1016/j.xpro.2023.102769
- id: doi:10.1016/j.xpro.2023.102769
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666166723007360-fx1.jpg

# 32. Mizumoto N.* (2023) TManual: Assistant for manually measuring length development in structures built by animals. Ecology and Evolution, 13(8):e10394, DOI: 10.1002/ece3.10394
- id: doi:10.1002/ece3.10394
  type: paper
  image: https://github.com/nobuaki-mzmt/tmanual/raw/main/images/output.gif

# 31  Mizumoto N.#*, Tanaka Y.#, Valentini G., Richardson O. T., Annagiri S., Pratt. C. S. & Shimoji H. (2023) Functional and mechanistic diversity in ant tandem runs. iScience, 26(4):106418, DOI: 10.1016/j.isci.2023.106418
- id: 10.1016/j.isci.2023.106418
  type: paper
  image: https://www.cell.com/cms/attachment/7c371333-2e51-4206-99f7-cf419502554c/fx1.jpg

# 2022
# 30  Mizumoto N.* & Bourguignon T. (2022) Light alters activity but do not disturb tandem coordination of termite mating pairs. Ecological Entomology, 48(2):145-153, DOI: 10.1111/een.13209
- id: 10.1111/een.13209
  type: paper
  image: https://resjournals.onlinelibrary.wiley.com/cms/asset/f68cdf04-0e37-4824-ba66-44d7dbc3248a/een13209-fig-0001-m.jpg

# 29  Mizumoto N.*, Bourguignon T., & Bailey W. N. (2022) Ancestral sex-role plasticity facilitates the evolution of same-sex sexual behavior. Proceedings of the National Academy of Science, 119(46):e2212401119, DOI: 10.1073/pnas.2212401119
- id: 10.1073/pnas.2212401119
  type: paper
  image: https://www.pnas.org/cms/10.1073/pnas.2212401119/asset/0802f2c7-810d-492b-984b-002c5211982c/assets/images/large/pnas.2212401119fig01.jpg

# 28. Lee S.B.*, Chouvenc T., Mizumoto N., Mullins A. & Su N.Y. (2022) Age-based spatial distribution of workers is resilient to worker loss in a subterranean termite. Scientific Reports, 12:7837, DOI: 10.1038/s41598-022-11512-1
- id: 10.1038/s41598-022-11512-1
  type: paper

# 27. Buček A., Wang M., Šobotník J., Sillam-Dussès D., Mizumoto N., Stiblík P., Clitheroe C., Lu T., González Plaza J. J., Mohagan A., Rafanomezantsoa J. J., Fisher B., Engel M., Roisin Y., Evans T., Scheffrahn R. & Bourguignon T.* (2022) Molecular phylogeny reveals the past transoceanic voyages of drywood termites (Isoptera, Kalotermitidae). Molecular Biology and Evolution, 39(5):msa093, DOI: 10.1093/molbev/msac093
- id: 10.1093/molbev/msac093
  type: paper

# 26. Mizumoto N.*, Bourguignon T. & Kanao T. (2022) Termite nest evolution fostered social parasitism by termitophilous rove beetles. Evolution, 76(5):1064-1072, DOI:10.1111/evo.14457
- id: 10.1093/molbev/msac093
  type: paper
  image: https://lh3.googleusercontent.com/mHKhp-uuZiAP6AgwdkKIKZkYkDsl-NSas04RtzbwykZXk53PJvOpfHXKEiNEA6NGikCAbdUQAVKsf9Bi1plQohpHGZ8I-9K426up9lAXgSbBBXfoNCZQxoVnf90918VZew=w1280

# 2021
# 25. Yashiro T.*, Tea Y-K., Wal C.V.D., Nozaki T., Mizumoto N., Hellemans S., Matsuura K. & Lo N. (2021) Enhanced heterozygosity from male meiotic chromosome chains is superseded by hybrid female asexuality in termites. Proceedings of the National Academy of Science, 118, e2009533118, DOI:10.1073/pnas.2009533118
- id: 10.1073/pnas.2009533118
  type: paper


# 24. Mizumoto N.* & Bourguignon T. The evolution of body size in termites. (2021) Proceedings of the Royal Society B, 288: 20211458, DOI: 10.1098/rspb.2021.1458
- id: 10.1098/rspb.2021.1458
  type: paper
  image: https://www.oist.jp/sites/default/files/styles/background_image_xl_low_1x/public/20220114-HeaderImage-AColonyOfTermites.jpg?h=56b840cf&itok=_CJhu3rn

# 23. Mizumoto N.*, Lee S.B., Valentini G., Chouvenc T. & Pratt S.C. (2021) Coordination of movement via complementary interactions of leaders and followers in termite mating pairs. Proceedings of the Royal Society B, 288:20210998, DOI:10.1098/rspb.2021.0998
- id: 10.1098/rspb.2021.0998
  type: paper
  image: https://lh4.googleusercontent.com/R0Mt3WJYCzr5OxSgGhl87NtYH4YcEorwA4G-hE51onN2pTf0goLYQ0LpfDNN_76Boy0m3d1L7lFoyew2u9lcQQ4o0HuVjCLU8b9or6xyZL5YzDpvdwGq274Rcvdm5UYC3g=w1280

# 2020
# 22. Taerum S.J.*, Jasso-Selles D.E., Hileman J.T., De Marini F., Mizumoto N. & Gile G.H. (2020) Spirotrichonymphea symbionts of the termite Paraneotermes simplicicornis.  European Journal of Protistology, 76: 125742, DOI:10.1016/j.ejop.2020.125742
- id: 10.1016/j.ejop.2020.125742
  type: paper

# 21. Mizumoto N.*, Rizo A., Pratt S.C. & Chouvenc T. (2020) Termite males enhance mating encounters by changing speed according to density. Journal of Animal Ecology, 89: 2542-2552, DOI:10.1111/1365-2656.13320 
- id: 10.1111/1365-2656.13320 
  type: paper

# 20. Valentini G., Mizumoto N., Pratt S.C., Pavlic T.P.* & Walker S.I.* (2020) Revealing the structure of information flows discriminates similar animal social behaviors. eLife, 9:e55395, DOI:10.7554/eLife.55395
- id: 10.7554/eLife.55395
  type: paper

#19. Mizumoto N.*, Gile G. H. & Pratt S.C. (2020) Behavioral rules for soil excavation by colony founders and workers in termites. Annals of the Entomological Society of America, 114(5):654-661, DOI:10.1093/aesa/saaa017
- id: 10.1093/aesa/saaa017
  type: paper
  image: https://lh5.googleusercontent.com/Ojv44KfKGayQkj5tRSWnVRwno5gxeB7ye1fiVRuqYpKxk9KwejT-Ms1pxrTZ4mqYrLeX3nugkVoFmJEezTIVgo2Wi52FJJpQkWbfFjGhsNjExf7bL12N_Ddn_UVEK8nHDg=w1280

#18. Mizumoto N.*, Bardunias P.M. & Pratt S.C. (2020) Complex relationship between tunneling patterns and individual behaviors in termites. American Naturalist, 196(5): 555-565, DOI:10.1086/711020
# 17. Mizumoto N.* & Bourguignon T. (2020) Modern termites inherited the potential of collective construction from their common ancestor. Ecology and Evolution, 10: 6775-6784 DOI:10.1002/ece3.6381
# 16. Mitaka Y.*, Matsuyama S., Mizumoto N., Matsuura K. & Akino T. (2020) Chemical identification of an aggregation pheromone in the termite Reticulitermes speratus. Scientific Reports 10: 7424 DOI:10.1038/s41598-020-64388-4
# 2019
# 15. Shimoji H.*#, Mizumoto N.#, Oguchi K. & Dobata S. (2019) Caste-biased locomotor activities in isolated termites. Physiological Entomology 45: 50-59 DOI:10.1111/phen.12315
# 14. Mee E. D., Gaylor M. G., Jasso-Selles D. E., Mizumoto N. & Gile G. H.* (2019) Molecular phylogenetic position of Hoplonympha natator (Trichonymphea, Parabasalia). Journal of Eukaryotic Microbiology 67: 268-272 DOI:10.1111/jeu.12765
# 13. Mizumoto N.*, Miyata S. & Pratt S. C. (2019) Inferring collective behavior from a fossilized fish shoal. Proceedings of the Royal Society B 286: 20190891 DOI: 10.1098/rspb.2019.0891
# 12. Mizumoto N.* & Dobata S. Adaptive switch to sexually dimorphic movements by partner-seeking termites. (2019) Science Advances 5: eaau6108 DOI: 10.1126/sciadv.aau6108
- id: 10.1126/sciadv.aau6108
  type: paper
  #image: https://lh6.googleusercontent.com/qzn-N75FRUx_MRWGFVu_cDwh5esZL4FheclHlCfgUDU78gGDoPOUsCxgoHYnVf3Xxk9LG6bDOh0M-0IKU-LxxfBYJLsSETAOUXqb_I1yhwEpR6o7hmFXc3QFenD0A8uVlg=w1280

# 2018
# 11. Mizumoto N. (2018) Barricade construction by primitive termites: Task allocation and evolutionary perspectives. Artificial Life and Robotics 23: 469-473 DOI:10.1007/s10015-018-0474-6

# 10. Yashiro T.*, Lo N., Kobayashi K., Nozaki T., Fuchikawa T., Mizumoto N., Namba Y. & Matsuura K. (2018) Loss of males from mixed-sex societies in termites BMC Biology 16: 96 DOI:10.1186/s12915-018-0563-y
- id: 10.1186/s12915-018-0563-y
  type: paper

# 9.  Mizumoto N.* & Dobata S. (2018) The optimal movement patterns for mating encounters with sexually asymmetric detection ranges. Scientific Reports 8: 3356 DOI:10.1038/s41598-018-21437-3
- id: 10.1086/711020
  type: paper
  #image: https://lh4.googleusercontent.com/4sYFurn62gAYuoaLOoVUnmO14HSBaDlFYKLiS__rG1vlGa5Gu_iI8gmknbZBLOiZ-XLHOIrNPxWyuUvM4nE1B36KO1lw719y3utCDj1RfNuDngOr9FT3wQJE61jTBJECAg=w1280

# 8.  Matsuura K.*#, Mizumoto N.#, Kobayashi K., Nozaki T., Fujita T., Yashiro T., Fuchikawa T., Mitaka Y. & Vargo E. L. (2018) A genomic imprinting model of termite caste determination: Not genetic but epigenetic inheritance influences offspring caste fate. The American Naturalists 191(6): 677-690 DOI:10.1086/697238
- id: 10.1086/697238
  type: paper

# 2017
# 7.  Hasegawa E.*#, Mizumoto N.#, Kobayashi K., Dobata S., Yoshimura J. Watanabe S., Murakami Y. & Matsuura K. (2017) Nature of collective decision-making by simple yes/no decision units. Scientific Reports 7:14436 DOI:10.1038/s41598-017-14626-z 
- id: 10.1038/s41598-017-14626-z 
  type: paper

# 6.  Mizumoto N.*, Fuchikawa T. & Matsuura K. (2017) Pairing strategy after today's failure: unpaired termites synchronize mate search using photic cycles. Population Ecology 59(3): 205-211. DOI:10.1007/s10144-017-0584-3 
- id: 10.1007/s10144-017-0584-3 
  type: paper

# 5.  Nagaya N.*#, Mizumoto N.#, Abe M. S., Dobata S., Sato R. & Fujisawa R.* (2017) Anomalous diffusion on the servosphere: a potential tool for detecting inherent organismal movement patterns. PLOS ONE 12(6): e0177480. DOI:10.1371/journal.pone.0177480 
- id: 10.1371/journal.pone.0177480 
  type: paper

# 4.  Mizumoto N.*, Abe M. S.* & Dobata S.* (2017) Optimizing mating encounters by sexually dimorphic movements. Journal of the Royal Society Interface 14: 20170086. DOI:10.1098/rsif.2017.0086
- id: 10.1098/rsif.2017.0086
  type: paper
  #image: https://lh5.googleusercontent.com/8r-UZU2CGkc2MiWDvZeOVTiSBG7J3b2ggPg-cNib8uPCqQxsi0vzzqfta0XSUJF0eSUnmphXP8F74zWSKAh72sc=w1280

# ~2016
# 3.  Mizumoto N.*, Yashiro T. & Matsuura K. (2016) Male same-sex pairing as an adaptive strategy for future reproduction in termites. Animal Behaviour 119: 179-187. DOI: 10.1016/j.anbehav.2016.07.007 
- id: 10.1016/j.anbehav.2016.07.007 
  type: paper
  #image: https://lh5.googleusercontent.com/H7VYXvtW7G8vg5B8G6-aQ_mXY2j0z0z1XZ0oQQ35dtGECaXa2Aurnnj8IC9jayfsxOFgVAn0u25_t3EBx4yArwBDH9G2HU-_A2bwtkn5vFhg9l09=w1280

# 2.  Mizumoto N.*, Kobayashi K. & Matsuura K. (2015) Emergence of intercolonial variation in termite shelter tube patterns and prediction of its underlying mechanism. Royal Society Open Science 2: 150360 DOI:10.1098/rsos.150360 
- id: 10.1098/rsos.150360
  type: paper
  #image: https://lh4.googleusercontent.com/OlOrNdIYwJts4LIpiDWhN0JRO_e7zIx9haxlcIwecvShT5C7wlU_ChOEA63xfLECxsp2EQ=w1280

# 1.  Mizumoto N. & Matsuura K.* (2013) Colony-specific architecture of shelter tubes by termites. Insectes Sociaux 60: 525-530. DOI:10.1007/s00040-013-0319-1 
- id: 10.1007/s00040-013-0319-1 
  type: paper
  #image: https://lh5.googleusercontent.com/ZI0ZoTYyMxMCb07fNBGCQyMjlcRL941s_jP-obvkiXjwzSJ74CDx4H06HIj4ErevBbeEj0qBLG4pdMOMexiWhk0m5PGIsiG076nQUm7hr3aG1NNs=w1280

